{% set name = "uiua" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/uiua-lang/uiua/archive/{{ version }}.tar.gz
  sha256: 8022449c3254dec85c2502b532507455d0eb86d7fa72c68efee05b3041fd09b4

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - make

test:
  commands:
    - uiua --help

about:
  home: https://github.com/uiua-lang/uiua
  license: MIT
  license_file:
    - license
    - THIRDPARTY.yml
  summary: A stack-based array programming language
  dev_url: https://github.com/uiua-lang/uiua

extra:
  recipe-maintainers:
    - danielnachun
